In [4]:
import pandas as pd

In [5]:
df =  pd.read_csv('Data sets - Spatial Data.csv')

In [6]:
df = df.drop(0)

In [7]:
df['Depth'] = pd.to_numeric(df['Depth'])

In [8]:
df['Baseline CH4 Production Rate'] = pd.to_numeric(df['Baseline CH4 Production Rate'])

In [9]:
df = df.drop(columns=['Solids'])

In [10]:
df = df.drop(columns=['Clay'])

In [11]:
df = df.drop(columns=['X'])

In [12]:
df = df.drop(columns=['Y'])

In [13]:
df

      Depth Baseline DOC   Baseline CH4 Production Rate
1      4.43        110.03                       0.01555
2      5.13        100.35                       0.01284
3      4.22        112.63                       0.01513
4      4.91         98.28                       0.01082
5      4.25        122.08                       0.02335
...     ...           ...                           ...
996    4.39        113.78                       0.02184
997    4.25        116.59                       0.01207
998    4.42         98.44                       0.01957
999    5.27        101.64                       0.01953
1000   2.95        107.58                       0.02012

[1000 rows x 3 columns]

In [14]:
df['Mass/kg'] = df['Depth'] * df['Baseline CH4 Production Rate']

In [15]:
df = df.sort_values(by='Mass/kg', ascending=False)

In [16]:
df

     Depth Baseline DOC   Baseline CH4 Production Rate   Mass/kg
799   5.76         89.91                       0.03364  0.193766
463   6.15        113.11                       0.03056  0.187944
581   6.40         96.67                       0.02836  0.181504
429   6.34        105.39                       0.02823  0.178978
960   5.56        100.47                       0.02912  0.161907
..     ...           ...                           ...       ...
177   4.73         89.66                       0.00805  0.038077
176   4.09        107.79                       0.00920  0.037628
183   3.09         110.1                       0.01202  0.037142
214   3.19         93.77                       0.01100  0.035090
743   2.69         85.98                       0.01299  0.034943

[1000 rows x 4 columns]

In [17]:
df['Energy/MJ']= 55.5 * 0.37 *  df['Mass/kg']

In [18]:
df

     Depth Baseline DOC   Baseline CH4 Production Rate   Mass/kg  Energy/MJ
799   5.76         89.91                       0.03364  0.193766   3.978993
463   6.15        113.11                       0.03056  0.187944   3.859430
581   6.40         96.67                       0.02836  0.181504   3.727185
429   6.34        105.39                       0.02823  0.178978   3.675317
960   5.56        100.47                       0.02912  0.161907   3.324764
..     ...           ...                           ...       ...        ...
177   4.73         89.66                       0.00805  0.038077   0.781901
176   4.09        107.79                       0.00920  0.037628   0.772691
183   3.09         110.1                       0.01202  0.037142   0.762707
214   3.19         93.77                       0.01100  0.035090   0.720573
743   2.69         85.98                       0.01299  0.034943   0.717557

[1000 rows x 5 columns]

In [19]:
df.head(100)

     Depth Baseline DOC   Baseline CH4 Production Rate   Mass/kg  Energy/MJ
799   5.76         89.91                       0.03364  0.193766   3.978993
463   6.15        113.11                       0.03056  0.187944   3.859430
581   6.40         96.67                       0.02836  0.181504   3.727185
429   6.34        105.39                       0.02823  0.178978   3.675317
960   5.56        100.47                       0.02912  0.161907   3.324764
..     ...           ...                           ...       ...        ...
113   5.76        117.15                       0.02121  0.122170   2.508753
696   5.05         95.28                       0.02415  0.121957   2.504397
281   5.47        127.58                       0.02223  0.121598   2.497017
817   4.84        108.12                       0.02508  0.121387   2.492686
389   5.38        129.34                       0.02252  0.121158   2.487971

[100 rows x 5 columns]

In [20]:
sum(df['Mass/kg'])

89.5811531

In [21]:
sum(df['Energy/MJ'])

1839.5489789085

In [22]:
df.to_csv('CH4_Emissions_Analysis.csv', index=False, encoding='utf_8_sig')

In [1]:
from IPython.display import FileLink
FileLink('CH4_Emissions_Analysis.csv')

/Users/huangqiushi/Developer/EngHack2026/CH4_Emissions_Analysis.csv